
version: '3.8'

services:
  nb-helper:
    env_file: nb-helper.env
    build:
      context: .
    image: nb-helper:latest
    restart: always
    ports:
      - "33050:5000"

  worker:
    env_file: nb-helper.env
    build:
      context: ./webhooks/queue
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes: ['./webhooks/queue:/queue']

  monitor:
    build:
      context: ./webhooks/queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
    volumes: ['./webhooks/queue:/queue']

  redis:
    image: redis
    ports:
      - "36379:6379"
    command:
    - redis-server --appendonly yes
    volumes:
    - redis-data:/data

volumes:
  redis-data:
    driver: local
