
version: '3.8'

services:
  nb-helper:
    env_file: nb-helper.env
    build:
      context: .
    image: nb-helper:latest
    restart: always
    ports:
      - "33050:5000"

  redis:
    image: redis
    ports:
      - "36379:6379"
    command:
    - redis-server --appendonly yes
    volumes:
    - redis-data:/data

volumes:
  redis-data:
    driver: local
